name: Sacred Crystal Meanings
favicon: null
layout_spectrum: 0.4855772592127323
typography_spectrum: 0.888431959785521
title: Sacred crystal energy and meanings boosted to the next level.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72819308-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#ffffff'
    - '#dfc7bb'
    - '#668bc2'
    - '#ffeb44'
  brandStrength: 0.3753779996186495
  lightness: 0.3144955050665885
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
